baseURL: "https://iacdrops.xyz"
languageCode: "en-us"
title: "Riyadh Uddin"
theme: "portfolio"
relativeURLs: true

#googleanalytics: UA-xxxxxx-x
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3
  customCSS: false

  favicon: "/images/iacdropslogo.png"
  description: "Riyadh Uddin portfolio"

  # Navbar Menus
  customMenus:
    - name: "Blog"
      Url: "/blog"

  # home
  disable_home: false
  profile_image: "/images/riyadhuddin.png"
  name: "Riyadh Uddin"
  namecolor: ffc107
  profession: "Developer"
  github: "https://github.com/riyadhuddin"
  gitlab: "https://gitlab.com/riyadhuddin"
  linkedin: "https://linkedin.com/in/riyadhuddin"
  twitter: "https://twitter.com/riyadhuddin_"
  instagram: "https://instagram.com/riyadh_uddin"
  facebook: "https://facebook.com/iacdrops"

  # About
  disable_about: false
  descripe_l1_person: "Hi, I'm Riyadh, a passionate application developer. I tend to make use of modern technologies to build apps that looks great, feels fantastic, and functions correctly."
  descripe_l2_person: "You can find my works [here](#projects)"
  skills:
    - name: Python
      percentage: 90
    - name: Flutter
      percentage: 65
    - name: Hugo
      percentage: 80
    - name: AWS
      percentage: 70

  # Experience
  disable_experience: false
  experience:
    - company: "iacdrops"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Software developer"
      startdate: November 2021
      enddate: present
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "rbiostudio"
      # id: "facebook-developer" // use this, when you want to change the id(used for navigation)
      role: "Fullstack developer"
      startdate: Mar 2020
      enddate: July 2021
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    

  # Education
  disable_education: false
  education:
    - degree: "BSc"
      branch: "Computer Science"
      university: "Premier university"
      startedyear: "2014"
      graduation: "2019"
    - degree: "MSc"
      branch: "Computer Science"
      university: "Brac university"
      startedyear: "2019"
      graduation: "2022"

  # Projects
  disable_projects: false
  # projects:
    #- name: "Example project without details"
     # img: /images/project.jpg
      #githublink: "https://github.com/riyadhuddin"
      #featuredlink: "https://iacdrops.xyz"
      #description: "Description of project ..."

  # Achievements
  disable_achievements: true
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      # url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "itssend@gmail.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: true
  tweet: true
